name: Create Project Zip File

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get repository name
      id: get_repo_name
      run: echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

    - name: Create the project zip file
      run: |
        # Use the 'zip' command to archive files, excluding the .git and .github directories
        zip -r NDS_MinUI.zip . -x .git/* .github/*
    - name: Upload the zip file as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: NDS_MinUI-archive
        path: NDS_MinUI.zip
        retention-days: 5
